import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PUBLIC=path.join(__dirname,'public');
const PORT=Number(process.env.PORT||8787);
const MODEL=process.env.OPENAI_MODEL||'gpt-5.6';
const EFFORT=process.env.OPENAI_REASONING_EFFORT||'high';
const API_KEY=process.env.OPENAI_API_KEY||'';
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8'};

function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store'});res.end(typeof body==='string'?body:JSON.stringify(body))}
function collect(req){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>2_000_000){reject(new Error('Request too large'));req.destroy()}});req.on('end',()=>resolve(data));req.on('error',reject)})}
function staticFile(req,res){let raw=new URL(req.url,'http://localhost').pathname;if(raw==='/')raw='/index.html';const file=path.normalize(path.join(PUBLIC,decodeURIComponent(raw)));if(!file.startsWith(PUBLIC)){send(res,403,'Forbidden','text/plain');return}fs.stat(file,(err,st)=>{if(err||!st.isFile()){send(res,404,'Not found','text/plain');return}const ext=path.extname(file);res.writeHead(200,{'Content-Type':MIME[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=300'});fs.createReadStream(file).pipe(res)})}

const schema={type:'object',properties:{
 session_grade:{type:'string'},session_assessment:{type:'string'},recommended_action:{type:'string',enum:['train','rest','train_modified']},
 key_takeaways:{type:'array',items:{type:'string'}},
 exercise_analysis:{type:'array',items:{type:'object',properties:{exercise_id:{type:'string'},exercise_name:{type:'string'},assessment:{type:'string'},decision:{type:'string',enum:['increase','hold','reduce','calibrate','modify','skip']},next_load_text:{type:'string'},next_sets:{type:'integer'},next_rep_min:{type:'integer'},next_rep_max:{type:'integer'},target_rir:{type:'number'},rest_min:{type:'number'},rationale:{type:'string'}},required:['exercise_id','exercise_name','assessment','decision','next_load_text','next_sets','next_rep_min','next_rep_max','target_rir','rest_min','rationale'],additionalProperties:false}},
 program_adjustments:{type:'array',items:{type:'string'}},recovery_flags:{type:'array',items:{type:'string'}},
 next_workout:{type:'object',properties:{code:{type:'string',enum:['A','B','C','D']},phase_note:{type:'string'},exercises:{type:'array',items:{type:'object',properties:{exercise_id:{type:'string'},exercise_name:{type:'string'},decision:{type:'string'},load_text:{type:'string'},sets:{type:'integer'},rep_min:{type:'integer'},rep_max:{type:'integer'},target_rir:{type:'number'},rest_min:{type:'number'},rationale:{type:'string'}},required:['exercise_id','exercise_name','decision','load_text','sets','rep_min','rep_max','target_rir','rest_min','rationale'],additionalProperties:false}}},required:['code','phase_note','exercises'],additionalProperties:false},
 coach_memory_update:{type:'string'}
},required:['session_grade','session_assessment','recommended_action','key_takeaways','exercise_analysis','program_adjustments','recovery_flags','next_workout','coach_memory_update'],additionalProperties:false};

function extractText(j){if(typeof j.output_text==='string')return j.output_text;for(const item of j.output||[]){for(const c of item.content||[]){if(c.type==='output_text'&&typeof c.text==='string')return c.text}}return ''}
function compactSessions(sessions){return (sessions||[]).slice(-12).map(s=>({date:s.date,code:s.code,bodyweight:s.bodyweight,duration:s.duration,totalWeightMoved:s.totalWeightMoved,readiness:s.readiness,doms:s.doms,dailyAdjustment:s.dailyAdjustment,painFlag:s.painFlag,painNotes:s.painNotes,pumps:s.pumps,notes:s.notes,phase:s.phase,exercises:(s.exercises||[]).map(e=>({id:e.id,name:e.name,note:e.note,sets:e.sets}))}))}
async function coach(body){
 if(!API_KEY)throw Object.assign(new Error('OPENAI_API_KEY is not configured on the server.'),{status:503});
 const state=body.state||{};const current=body.currentSession||{};const program=body.program||{};
 const system=`You are an experienced evidence-informed hypertrophy and strength coach. Your task is to make conservative, individualized programming decisions from actual workout logs, not merely apply a mechanical add-weight rule.\n\nPriorities:\n1. Long-term training consistency and joint/tissue tolerance.\n2. Hypertrophy as the primary goal while retaining useful strength.\n3. Respect the program roles: A primary back/upper chest; B primary quad; C chest/arms/delts with secondary back; D posterior/lower with secondary quad. Do not make every exposure equally hard.\n4. During re-entry after a layoff, use reduced volume and generally 3–4 RIR for the first two exposures of each workout. Do not chase historical PRs.\n5. Use load, reps, RIR, rest, pump, DOMS, readiness, pain notes, session duration, total weight moved and multi-session trends together. Pump is secondary; 6–8 is productive and 9–10 is not required. DOMS alone is not proof of a good workout.\n6. If the user reports sharp/localized pain or injury-like symptoms, do not diagnose. Modify/stop the provoking movement and recommend professional evaluation when symptoms are significant, recurrent or persistent.\n7. The shoulder historically dislikes overhead pressing; do not introduce it without a strong reason. Heavy RDLs/back squats historically irritated the low back/SI area. Front squats and low-incline dumbbell pressing were tolerated. Prior left hamstring strain recovered but warrants measured direct-loading progression and 24–48 hour response monitoring.\n8. Keep sessions around 50–60 minutes when practical; do not add volume just because the athlete can tolerate it.\n9. Use double progression: earn load increases by owning the rep range at the intended RIR. Do not increase load and volume simultaneously without a clear reason.\n10. Be precise and plainspoken. Do not manufacture PRs or facts not present in the logs.\n\nReturn only the structured output requested by the schema. The next_workout must normally be the rotation's next code unless recovery requires modification; if recommending rest, keep the next workout code unchanged and set recommended_action to rest.`;
 const user={training_profile:state.profileNotes,coach_memory:state.coachMemory,current_phase:state.phase,next_workout_planned:state.nextWorkout,exposures:state.exposures,current_session:current,recent_sessions:compactSessions(state.sessions),base_program:program};
 const payload={model:MODEL,reasoning:{effort:EFFORT},store:false,max_output_tokens:5000,input:[{role:'system',content:system},{role:'user',content:`Analyze the current session and prescribe the next workout using this training state:\n${JSON.stringify(user)}`}],text:{format:{type:'json_schema',name:'training_coach_review',strict:true,schema}}};
 const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Authorization':`Bearer ${API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});
 const j=await r.json();if(!r.ok){const msg=j?.error?.message||`OpenAI API error ${r.status}`;throw Object.assign(new Error(msg),{status:r.status})}const txt=extractText(j);if(!txt)throw new Error('No structured output returned.');return JSON.parse(txt);
}

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/api/health'){send(res,200,{ok:true,ai:!!API_KEY,model:API_KEY?`${MODEL} (${EFFORT})`:null});return}if(u.pathname==='/api/coach'&&req.method==='POST'){const raw=await collect(req);const body=JSON.parse(raw||'{}');const review=await coach(body);send(res,200,{review});return}if(u.pathname.startsWith('/api/')){send(res,404,{error:'Unknown API route'});return}staticFile(req,res)}catch(e){send(res,e.status||500,{error:e.message||'Server error'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`Training Coach AI running at http://localhost:${PORT} | AI ${API_KEY?'enabled':'disabled'} | model ${MODEL}`));
